In [2]:
import pandas as pd 
import numpy as np
import matplotlib as plt
import seaborn as sns

In [9]:
house_df = pd.read_csv("C:/Users/91984/Downloads/Luxury_Housing_Bangalore (1).csv", encoding="utf-8")
house_df.head(7)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.75084604,Primary,NRI,31-03-2025,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.29215187,Primary,Other,30-06-2024,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.51772441,Primary,HNI,31-12-2023,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494,Primary,HNI,31-03-2024,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.34539244,Secondary,HNI,31-12-2024,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
5,PROP000006,YELAHANKA,Project_5,Brigade,4290.0,4bhk,₹9.82 Cr,Secondary,HNI,30-09-2023,7.936068,NaN,Launch,Online,no,5.154027,16,Underpriced for location.
6,PROP000007,Bannerghatta Road,Project_6,Prestige,6776.0,5BHK+,10.89675235,Secondary,Other,31-03-2025,8.643117,8.355238,Under construction,Direct,no,9.791550,74,Too far from my office.

In [10]:
house_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [11]:
house_df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [12]:
house_df.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [13]:
tmp_df = house_df.copy()
tmp_df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.75084604,Primary,NRI,31-03-2025,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.29215187,Primary,Other,30-06-2024,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.51772441,Primary,HNI,31-12-2023,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494,Primary,HNI,31-03-2024,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.34539244,Secondary,HNI,31-12-2024,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004,Secondary,CXO,31-12-2024,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.82937316,Primary,CXO,30-09-2024,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.18330315,Primary,NRI,31-12-2023,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.91415638,Secondary,Other,30-06-2024,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,31-12-2023,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [14]:
tmp_df['Micro_Market']=tmp_df['Micro_Market'].str.title().str.strip()
tmp_df['Configuration']=tmp_df['Configuration'].str.upper().str.strip()
tmp_df['NRI_Buyer'] = tmp_df['NRI_Buyer'].str.capitalize().str.strip()
tmp_df['Project_Name'] = tmp_df['Project_Name'].str.replace('_',' ',regex=False).str.strip()

tmp_df['Unit_Size_Sqft'] = tmp_df['Unit_Size_Sqft'].replace(-1, pd.NA)
tmp_df['Unit_Size_Sqft'] = pd.to_numeric(tmp_df['Unit_Size_Sqft'], errors='coerce')
tmp_df['Unit_Size_Sqft'] = tmp_df['Unit_Size_Sqft'].astype(float)

tmp_df['Purchase_Quarter'] = pd.to_datetime(tmp_df['Purchase_Quarter'], dayfirst=True, errors='coerce')

tmp_df['Ticket_Price_Cr'] = (tmp_df['Ticket_Price_Cr'].astype(str).str.replace('₹', '', regex=False).str.replace('Cr', '', regex=False).str.strip())
tmp_df['Ticket_Price_Cr'] = pd.to_numeric(tmp_df['Ticket_Price_Cr'], errors='coerce')

tmp_df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project 0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,Yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project 1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,No,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project 2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,Yes,6.985493,113,Agent was not responsive.
3,PROP000004,Bellary Road,Project 3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,Yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project 4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,No,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,Bellary Road,Project 229,Embassy,8546.0,5BHK+,11.330810,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,No,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project 309,Brigade,3408.0,3BHK,10.829373,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,No,9.851849,26,Agent was not responsive.
100997,PROP065099,Hennur Road,Project 98,RMZ,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,No,9.101604,44,Loved the amenities!
100998,PROP093022,Rajajinagar,Project 21,Embassy,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,Yes,8.588551,66,Excellent location!
100999,PROP023826,Whitefield,Project 325,L&T Realty,3218.0,4BHK,13.270000,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,Yes,9.917647,58,Loved the amenities!

In [15]:
tmp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90449 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   float64
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  datetime64[ns]
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(11)
memory usage: 13.9+ MB

In [16]:
tmp_df.describe()

,Unit_Size_Sqft,Ticket_Price_Cr,Purchase_Quarter,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90449.000000,90981.000000,101000,101000.000000,90910.000000,101000.000000,101000.000000
mean,6005.625093,12.718336,2024-05-15 06:47:26.922772224,6.992619,7.503663,7.498426,67.182921
min,3000.000000,-1.420000,2023-06-30 00:00:00,4.000031,5.000224,5.000013,15.000000
25%,4504.000000,10.010392,2023-09-30 00:00:00,5.494526,6.260329,6.247954,41.000000
50%,6004.000000,12.037647,2024-03-31 00:00:00,6.985805,7.499123,7.495614,67.000000
75%,7505.000000,14.094726,2024-09-30 00:00:00,8.490000,8.752207,8.749824,93.000000
max,8999.000000,100.000000,2025-03-31 00:00:00,9.999970,9.999865,9.999956,119.000000
std,1731.456179,7.665803,NaN,1.731757,1.440758,1.443128,30.271611

In [17]:
tmp_df.loc[tmp_df['Ticket_Price_Cr'] < 0, 'Ticket_Price_Cr'] = np.nan

In [18]:
#print(tmp_df.info())
print(tmp_df.isnull().sum())
#tmp_df = tmp_df.dropna(subset=['Ticket_Price_Cr'])

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10551
Configuration               0
Ticket_Price_Cr         10024
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [19]:
# Treating Null Values
tmp_df['Ticket_Price_Cr'] = tmp_df['Ticket_Price_Cr'].fillna(tmp_df['Ticket_Price_Cr'].median())
tmp_df['Unit_Size_Sqft'] = tmp_df['Unit_Size_Sqft'].fillna(tmp_df['Unit_Size_Sqft'].median())
tmp_df['Amenity_Score'] = tmp_df['Amenity_Score'].fillna(tmp_df['Amenity_Score'].median())
tmp_df['Buyer_Comments'] = tmp_df['Buyer_Comments'].fillna("No Comment")

In [20]:
cat_cols = ['Builder', 'Micro_Market', 'Configuration',
            'Possession_Status', 'Sales_Channel', 'Buyer_Type']
for col in cat_cols:
    if col in tmp_df.columns:
        tmp_df[col] = tmp_df[col].fillna(tmp_df[col].mode()[0])

In [21]:
#Price_per_Sqft
tmp_df['Price_per_Sqft'] = (tmp_df['Ticket_Price_Cr'] * 1e7) / tmp_df['Unit_Size_Sqft']

#Quarter_Number
tmp_df['Quarter_Number'] = tmp_df['Purchase_Quarter'].dt.quarter

#Booking_Flag
tmp_df['Booking_Flag'] = tmp_df['Transaction_Type'].apply(
    lambda x: 1 if str(x).lower() in ['primary', 'secondary'] else 0
)
tmp_df['NRI_Buyer'] = tmp_df['NRI_Buyer'].map({'Yes': 1, 'No': 0})

In [22]:
tmp_df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft,Quarter_Number,Booking_Flag
0,PROP000001,Sarjapur Road,Project 0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,5.462863,Launch,Broker,1,9.212491,18,Loved the amenities!,31679.120596,1,1
1,PROP000002,Indiranagar,Project 1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,7.499123,Under construction,NRI Desk,0,7.723898,106,No Comment,28284.985885,2,1
2,PROP000003,Bannerghatta Road,Project 2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,8.669227,Ready to move,Direct,1,6.985493,113,Agent was not responsive.,13646.976009,4,1
3,PROP000004,Bellary Road,Project 3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,5.720246,Ready to move,Online,1,6.100929,106,Excellent location!,15175.012103,1,1
4,PROP000005,Koramangala,Project 4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,8.609649,Under construction,Broker,0,5.312510,18,Too far from my office.,21471.096180,4,1

In [23]:
tmp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        101000 non-null  float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       101000 non-null  float64
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  datetime64[ns]
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         101000 non-null  float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  int64
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        101000 non-null  object
 18  Price_per_Sqft        101000 non-null  float64
 19  Quarter_Number        101000 non-null  int32
 20  Booking_Flag          101000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int32(1), int64(3), object(10)
memory usage: 15.8+ MB

In [24]:
tmp_df.to_csv("cleaned_bangalore.csv", index=False)

In [26]:
import mysql.connector

conn_mysql = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345",
    database="realestate_db"
)
cursor_mysql = conn_mysql.cursor()
print("MySQL connection established!")

MySQL connection established!

In [27]:
data_list = tmp_df.values.tolist()

# Insert query
query = """
    INSERT IGNORE INTO real_estate_projects (
        Property_ID, Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft,
        Configuration, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter,
        Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer,
        Locality_Infra_Score, Avg_Traffic_Time_Min, Buyer_Comments,
        Price_per_Sqft, Quarter_Number, Booking_Flag
    )
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
"""

cursor_mysql.executemany(query, data_list)
conn_mysql.commit()
print("Data inserted using to_list()")

Data inserted using to_list()

In [28]:
cursor_mysql.close()
conn_mysql.close()